name: Deploy DevOps Chatbot

on:
  push:
    branches: [ "main" ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Docker
      uses: docker/setup-buildx-action@v2

    - name: Build Docker image
      run: docker build -t devops-chatbot .

    - name: Push code to EC2 and deploy
      uses: appleboy/ssh-action@v0.1.10
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ubuntu
        key: ${{ secrets.EC2_SSH_KEY }}
        script: |
          cd ~/devops-chatbot
          git pull origin main
          docker stop chatbot || true
          docker rm chatbot || true
          docker build -t devops-chatbot .
          docker run -d -p 8501:8501 --name chatbot devops-chatbot
